PREFIXES:
  GAME: '&8[&b&lFrozedRun&8] '
INFORMATIONS:
  WEB: www.frozed.club
  IP: frozed.club
  TS: ts.frozed.club
  STORE: store.frozed.club
  SERVER: FUR-1
MINIMUM-PLAYERS-TO-START-GAME: 2
MAXIMUM-PLAYERS-PER-GAME: 64
BORDER:
  SIZE: 250
REBOOT_COMMAND: stop

